### ISSUE TITLE
Can't compile due to `use of unstable library feature 'float_bits_conv'`

### ISSUE THREAD

**Issue by onelson** [RustAudio/lewton#21]
Error message pointed at rust-lang/rust#40470

I'm seeing this on stable, and nightly.

**Comment by est31** [comment]
@onelson which version of lewton do you use? Also, have you checked whether the `nightly` feature is enabled? If yes, it only works on nightly.

**Comment by onelson** [comment]
@est31 ha, yes!
I was seeing the issue on nightly, but I just checked the version, and it looks like rodio is depending on 0.5.0. I'll open something there to get them updated to your latest.

Sorry to bother you!

**Comment by est31** [comment]
@onelson no problem! The 0.5 branch should contain the fix as well, but you need to have at least version 0.5.1. Maybe a simple cargo update does it for you :). Best would be to change rodio to depend on either 0.5.1 or 0.6 versions of lewton.

**Comment by onelson** [comment]
Yeah, nothing needed changing. Rodio specifies "0.5" so, as you said, `cargo update` was all I needed. Thanks again!
