### ISSUE TITLE
Async API hangs

### ISSUE THREAD

**Issue by tuxmark5** [RustAudio/lewton#22]
Hello,

I've been trying to make use of the async api of lewton. However it doesn't seem to work currently, as the future for fetching headers currently hangs and never returns:
```
let data_reader = StreamReader::new(stream);
let mut header_reader = HeadersReader::new(data_reader);
println!("Start fetching headers");
let headers = await_borrow!(header_reader)?;
println!("This point is never reached");
let stream_reader = OggStreamReader::new(header_reader, headers);
```

**Comment by est31** [comment]
@tuxmark5 thanks for your report. Do you have a minimal runnable example?

**Comment by tuxmark5** [comment]
It's kinda hooked into my codebase right now, but I'm sure I will be able to extract the relevant parts to make such runnable example.

**Comment by tuxmark5** [comment]
Here's the minimap example: [lewton_test.tar.gz](https://github.com/RustAudio/lewton/files/1507910/lewton_test.tar.gz)

You'll need a sample test.ogg there. The basic gist of how things work there:
1. test.ogg is read and then is sent to unbounded channel.
2. The other end of the channel is used as a stream with a single Vec<u8> that contains the whole file.
3. StreamReader wraps is an adapter that can wrap Stream with Item=Vec<v8> and convert them into AsyncRead.
4. This AsyncRead is then given to HeadersReader::new
5. Which is a future that never completes, hence the bug report.

**Comment by est31** [comment]
@tuxmark5 thanks, I'll have a look soon :)

**Comment by tuxmark5** [comment]
The way I understand the issue is this: HeaderReader should return Async::NotReady if, and only if it receives ErrorKind::WouldBlock from it's reader. Otherwise it must return some data, or report an error if something went wrong. But because now it returns Async::NotReady, it causes the task that is executing the future to be parked permanently, because there is nothing to wake it up once it's parked.

**Comment by est31** [comment]
I see what you mean. Yes, that seems to be the issue.

**Comment by est31** [comment]
@tuxmark5 I have pushed a commit to fix the issue. Please write if it doesn't fix the issue for you despite fixing it for me. Do you need a release on crates.io?

**Comment by est31** [comment]
Thanks for the report.

**Comment by tuxmark5** [comment]
Nah, I don't need it on crates.io, but thanks for the offer.

**Comment by tuxmark5** [comment]
Seems to work great now. Thanks for the fix. 

One thing that I don't like and that could be improved is the usage of HeadersReader future:
Generally, every time you wait for the future to complete, it gets consumed (in futures library). Right now in the async lewton API this is not the case: you first wait for the future and then reuse that object again. This is why I wrote the await_borrow! macro, because letwon API doesn't follow the patterns established in futures crate. 
What should be happening in my opinion is that the HeadersReader should not only return the header set, but also itself, sort of like it works with Sink::send method in futures crate: [http://alexcrichton.com/futures-rs/futures/sink/trait.Sink.html#method.send](url)
This change would also allow chianing HeadersReader future with futures combinators like and_then, map and others, as once you wrap something with and_then there is no way to get the object back.

**Comment by tuxmark5** [comment]
In other words, I should be able to write something like this:
```
let stream = HeadersReader::new(data_reader)
  .and_then(|(reader, headers)| OggStreamReader::new(reader, headers))
  .flatten_stream();

#[async]
for packet_block in stream {
  for packet in packet_block {
    stream_yield!(packet);
  }
}
```

**Comment by est31** [comment]
@tuxmark5 sorry, back when I wrote the async part of lewton, there was no documentation about how to do libraries for async code. I had to figure out stuff on my own and this is the result :). Could you file a separate issue on that? I'll look at it at a later point in time.
