### ISSUE TITLE
Panic on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/lewton#27]
I have recently discovered that previous fuzzing attempts on lewton (namely the lewton target in https://github.com/rust-fuzz/targets) were using the OGG stream API and did not disable CRC32 check in `ogg` crate. This caused almost any fuzzer input to be rejected due to crc32 mismatch, rendering fuzzers useless.

I have [patched](https://github.com/Shnatsel/ogg/commit/818731bcf8ebb99537fe36459f5621964bf4eba6) the ogg crate to disable crc32 check during fuzzing. After this [honggfuzz-rs](https://github.com/rust-fuzz/honggfuzz-rs) has immediately discovered an input that causes an out-of-bounds access in lewton. Thanks to Rust's memory safety guarantees this is not a critical security issue (like it would be in C), but it could still be used to perform a denial-of-service attack.

The panic message is `index out of bounds: the len is 128 but the index is 1023` at line 1098 in `audio.rs`. The file triggering the crash [is attached](https://github.com/RustAudio/lewton/files/2119835/SIGABRT.PC.7ffff7203428.STACK.18f35adbaa.CODE.-6.ADDR.nil.INSTR.cmp____.0xfffffffffffff000.rax.fuzz.gz), I had to gzip it so that github would accept the upload. You should be able to reproduce the crash by disabling crc32 in unconditionally in a local copy of `ogg` crate and feeding this file to lewton.

My fuzzing setup is available at https://github.com/Shnatsel/lewton-fuzz, more info on using it can be found in the [rust-fuzz/targets issue](https://github.com/rust-fuzz/targets/issues/125). This panic is blocking any further fuzzing attempts. I will run another round of fuzzing once this panic is resolved.

**Comment by est31** [comment]
@Shnatsel could you try to minify that example in some way? 100 kb is a bit large, I'm sure it can be triggered by a shorter example.

**Comment by Shnatsel** [comment]
[minimized_testcase.ogg.gz](https://github.com/RustAudio/lewton/files/2172919/minimized_testcase.ogg.gz) courtesy of [AFL](https://github.com/rust-fuzz/afl.rs)s testcase minimization mode

**Comment by est31** [comment]
@Shnatsel thanks!

**Comment by est31** [comment]
@Shnatsel that file gives me an error and not a a panic. It says `BadHeader(EndOfPacket)`.

**Comment by Shnatsel** [comment]
You probably haven't disabled checksum verification in `ogg` crate. You need to use the latest `ogg` crate from git and build with `--cfg fuzzing` flag to rustc so that checksum verification actually gets disabled.

**Comment by est31** [comment]
Then I'd get a hash mismatch error. I actually can reproduce the panic with the 100kb example.

@Shnatsel this is what I did: `cargo run --example perf path/to/file.ogg` while turning off checksum verification.

**Comment by Shnatsel** [comment]
Hmm, in that case something is probably off with afl instrumentation. I have noticed that it detects considerably less distinct paths that cargo-fuzz (libfuzzer) even though they should be using pretty much the same thing.

**Comment by est31** [comment]
@Shnatsel any news with a new minimal reproducable example?

**Comment by Shnatsel** [comment]
I've narrowed it down to 21kb so far. I'll see if I can reduce it further.

[21kb_crashing_input.ogg.gz](https://github.com/RustAudio/lewton/files/2345361/21kb_crashing_input.ogg.gz)

**Comment by Shnatsel** [comment]
Ah, turns out the enormous allocations were throwing off AFL too. After I've disabled all memory limits `afl tmin` got the testcase down to 5kb.

[#27_really_minimized_testcase.ogg.gz](https://github.com/RustAudio/lewton/files/2346251/27_really_minimized_testcase.ogg.gz)

**Comment by est31** [comment]
Thanks @Shnatsel for reducing the testcase. I'm pushing a fix shortly.
[Link](https://github.com/RustAudio/lewton/files/2360228/27_really_minimized_testcase.ogg.zip) to the unpacked, but renamed file (to include .zip) so that it can be downloaded automatically.

**Comment by est31** [comment]
The bug is fixed now, still working on a regression test.

**Comment by est31** [comment]
Okay, using this file now instead: [27_really_minimized_testcase_crcfix.ogg.zip](https://github.com/RustAudio/lewton/files/2363013/27_really_minimized_testcase_crcfix.ogg.zip)
