### ISSUE TITLE
`async` feature doesn't work with Rust 2018

### ISSUE THREAD

**Issue by Bobo1239** [RustAudio/lewton#28]
Rust 2018 will add `async` as a keyword so you get this error when compiling:
```
error: expected identifier, found reserved keyword `async`
  --> sound/src/lib.rs:20:25
   |
20 | use lewton::inside_ogg::async::{OggStreamReader, HeadersReader};
   |                         ^^^^^ expected identifier, found reserved keyword
```
I can make a PR which just changes the module name if you tell me what you want.

**Comment by est31** [comment]
Thanks for the report. Fixed by 24133914a27efe7468cfab61e02dab16e8e99fc4 . Also pushed a new release, version 0.9.0.
