### ISSUE TITLE
Another panic on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/lewton#33]
When given a malformed input lewton panics with the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 256 but the index is 256', src/audio.rs:558:13
```

Testcase: [minimized_panic2_testcase.gz](https://github.com/RustAudio/lewton/files/2361413/minimized_panic2_testcase.gz) (gzipped so that github would accept the upload)

Command to reproduce the crash: 
`RUSTFLAGS='--cfg=fuzzing' cargo run --release --example perf /path/to/testcase` 

Tested on git commit ddd2408c80f5d206246f8273cbf9df73238e64d6. Found using [afl.rs](https://github.com/rust-fuzz/afl.rs)

**Comment by est31** [comment]
Repacked version: [33_minimized_panic_testcase.ogg.zip](https://github.com/RustAudio/lewton/files/2363173/33_minimized_panic_testcase.ogg.zip)

@Shnatsel btw, which are the license terms of the samples that were, will and are being submitted by you in the bug reports? Is [cc0](https://creativecommons.org/publicdomain/zero/1.0/) okay?

**Comment by Shnatsel** [comment]
Yeah, they're autogenerated by a tool I'm using, so I'm the copyright holder. I hereby release them under Creative Commons Zero 1.0.

**Comment by est31** [comment]
@Shnatsel thanks!

**Comment by est31** [comment]
Hmmm turns out the file was actually valid, not malformed. But the panic is a bug nontheless.
