### ISSUE TITLE
Create a C API so that C users can use lewton

### ISSUE THREAD

**Issue by est31** [RustAudio/lewton#37]
Needed by https://bugzilla.mozilla.org/show_bug.cgi?id=1446654

**Comment by bemeurer** [comment]
@est31 I've been doing a lot of this at work lately, I can help with this :)

**Comment by est31** [comment]
@bemeurer thanks for the help! You are good to go. Some hints/notes:

* [It was suggested](https://bugzilla.mozilla.org/show_bug.cgi?id=1446654#c2) to mimic the libvorbis C API as close as possible.
* [This](https://searchfox.org/mozilla-central/source/dom/media/platforms/agnostic/VorbisDecoder.cpp) is the part of the Firefox codebase that interfaces with libvorbis. Notably, it doesn't use the libvorbisfile API but the per-packet API ([this](https://github.com/xiph/vorbis/blob/master/include/vorbis/codec.h) header file) and does its own muxing. For us this means that we don't need the `ogg` integration or `inside_ogg` module or anything. In fact this is really good because our `ogg` integration has some half-baked features like only coarsely working seeking support (#16).
* I've created a repo for the result [here](https://github.com/RustAudio/clewton).

**Comment by bemeurer** [comment]
I was planning on using [`cbindgen`](https://github.com/eqrion/cbindgen) enabled through a cargo feature in this same crate. The crate would have an `ffi.rs` module which would only get included when the feature is enabled. 

What do you think of this approach, as opposed to a separate crate?

**Comment by est31** [comment]
I don't have much experience with exposing C APIs for Rust crates. I've suggested a separate crate because this is what rav1e did: https://github.com/lu-zero/crav1e . It seems to consist of a Rust wrapper around the rav1e API that is then translated via cbindgen. This allows them to make the API be very C-like. Probably all of this would have been possible inside the rav1e crate as well.

@lu-zero do you know why crav1e is a separate project from rav1e?

My main concern is that people who don't use the C API shouldn't be affected by this negatively through e.g. additional dependencies. If the deps are opt in, there don't seem to be any negative consequences, so, putting the C API into lewton is fine by me.

**Comment by lu-zero** [comment]
The rav1e `build.rs` is already crowded so a separate crate was the easiest solution.

**Comment by bemeurer** [comment]
@est31 Deps will only be brought in when you enable the `bindgen` feature. Since we don't have the issue @lu-zero mentioned, I think either path is just as good. Since you're the maintainer, I think it's a call for you to make, not me :)

**Comment by est31** [comment]
@bemeurer still want to do it? Or did the tabs scare you off :).

**Comment by est31** [comment]
Hmmm seems I'll have to remove cbindgen again because its MSRV policy [seems to be incompatible](https://github.com/eqrion/cbindgen/commit/191d8ca91735c30916edfd55f96678f34d2b5953).

**Comment by lu-zero** [comment]
API wise here is my proposal:

- [ ] Have the following opaques `Context`, `Samples`
- [ ] have a `lewton_context_from_extradata(data: *const u8, len: usize) -> *mut Context` as the main setup (mapping the first half of VorbisDataDecoder::Init())
- [ ] have a `lewton_context_reset(ctx: *mut Context) -> c_int` to reset the decoder state on seek
- [ ] have getters to take from the Context the stream information (rate, channels)
- [ ] have a main decoding function in the shape of `lewton_decode_packet(ctx: *mut Context, pkt: *const u8, len: usize, sample_out: *mut *mut Samples) -> c_int`
- [ ] have accessor in the shape of 
  - `lewton_samples_f32(sample: *const Sample, channel: usize) -> *const f32`
  - `lewton_samples_count(sample: *const Sample) -> usize`
- [ ] Destructors for both Structs

This should be enough for firefox from my first look at it.

**Comment by est31** [comment]
@lu-zero I've pushed an implementation to master (5aa3d2e031e1e50c77b7616e429d0ddfe24e6b9c). Could you please test whether it works? Thank you :)

**Comment by lu-zero** [comment]
Everything compiles as intended, we should tweak a little one detail to be more compatible (right now it generates the C++ header).

**Comment by lu-zero** [comment]
https://github.com/RustAudio/lewton/pull/51 should address that.

**Comment by est31** [comment]
Release 0.10.0 should address everything now I think.
