### ISSUE TITLE
panic in `residue_packet_decode_inner`

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/lewton#42]
lewton panics in `residue_packet_decode_inner` given crafted input. Error message: 
'index 21 out of range for slice of length 16' and similar with varying indices and lengths.

Steps to reproduce:
`RUSTFLAGS='--cfg=fuzzing' cargo run --release --example perf /path/to/file.ogg`

Sample files triggering the crash: [oor-panic-in-residue_packet_decode_inner.zip](https://github.com/RustAudio/lewton/files/2898246/oor-panic-in-residue_packet_decode_inner.zip)

Found with [AFL.rs](https://github.com/rust-fuzz/afl.rs).

**Comment by est31** [comment]
Hmm so this bug is weird. When I check whether `codebook_dimensions + partition_size > vec_v.len()` beforehand, the unit tests start failing. So I need to put the check into the loop :/. Let's just make the error silent.

**Comment by est31** [comment]
The repacked test samples are:

* [bug-42-sample009.ogg.zip](https://github.com/RustAudio/lewton/files/2905014/bug-42-sample009.ogg.zip)
* [bug-42-sample012.ogg.zip](https://github.com/RustAudio/lewton/files/2905017/bug-42-sample012.ogg.zip)
* [bug-42-sample015.ogg.zip](https://github.com/RustAudio/lewton/files/2905018/bug-42-sample015.ogg.zip)
* [bug-42-sample016.ogg.zip](https://github.com/RustAudio/lewton/files/2905019/bug-42-sample016.ogg.zip)
* [bug-42-sample029.ogg.zip](https://github.com/RustAudio/lewton/files/2905020/bug-42-sample029.ogg.zip)
