### ISSUE TITLE
Infinite loop on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/lewton#46]
Lewton enters an apparently infinite loop on decoding this file: [lewton-infinite-loop.ogg.zip](https://github.com/RustAudio/lewton/files/2923055/lewton-infinite-loop.ogg.zip)

Steps to reproduce:
`RUSTFLAGS='--cfg=fuzzing' cargo run --release --example perf /path/to/file.ogg`

Tested on commit 907806061e9ca620de3ee4b3684f05e34fd276c6. Found with AFL.rs

**Comment by est31** [comment]
The repacked sample is: [bug-46-sample001.ogg.zip](https://github.com/RustAudio/lewton/files/2923287/bug-46-sample001.ogg.zip)
