### ISSUE TITLE
Compilation fails in cross-compiling environment

### ISSUE THREAD

**Issue by Mitschmaster** [RustAudio/lewton#47]
i cross compile a rust/cargo project with travis ci on github. lewton is a dependancy there. but the compilation always fails. it gives a wrong elf format error.
version is v0.9.4
target arm-unknown-linux-gnueabihf

[build.log](https://github.com/RustAudio/lewton/files/3240249/build.log)

**Comment by est31** [comment]
I think it's because you are using the native linker `cc` instead of the cross linker. For some reason, this doesn't seem to have the effect needed: https://github.com/Mitschmaster/spotifyd/blob/082995c3e6dcb140603a2b855ebdca65f62fc2c5/.travis.yml#L13

**Comment by Mitschmaster** [comment]
sorry it was my bad. i set the linker wrong. as it is now in the repository it works.

**Comment by benmarten** [comment]
Awesome! Thanks for reporting this.. Was about to file a ticket, but your link saved me, added this to my Dockerfile worked:
`ENV RUSTFLAGS="-C linker=arm-linux-gnueabihf-gcc"`
