### ISSUE TITLE
The test assets fail to download

### ISSUE THREAD

**Issue by lu-zero** [RustAudio/lewton#80]
See https://github.com/RustAudio/lewton/pull/79/checks?check_run_id=779935432#step:6:140

**Comment by est31** [comment]
It seems only the xiph assets are affected, so the ones under [this](https://people.xiph.org/~xiphmont/test-vectors/vorbis/) URL. When I visit people.xiph.org, I'm getting a "Unavailable This website is experiencing techincal problems. Sorry for the inconvenience." message. Maybe only a temporary issue?

If it is a permanent downtime, I've archived the assets a while ago on the internet archive. Here's a list of links: http://web.archive.org/web/*/https://people.xiph.org/~xiphmont/test-vectors/vorbis/*

Also, I have it all stored locally on my computer :).

**Comment by TonalidadeHidrica** [comment]
After 3.5 months, the site still seems to be unavailable.

**Comment by lu-zero** [comment]
we should report upstream the problem and/or store them somewhere else, a similar problem got fixed for opus recently.

**Comment by est31** [comment]
I've originally wanted to update the URLs to the new home but if there is no change maybe we should just create a git submodule or whatever. I just dont want the assets to be part of the main git repo.

**Comment by nico-abram** [comment]
The bitbucket links also seem to be down

**Comment by est31** [comment]
I've rehosted the xiph test assets on github: https://github.com/RustAudio/lewton-test-assets

This issue is fixed by commit: 9337d897107816b328e8aeaf3986bd50e8d4c698
