### ISSUE TITLE
example/player.rs failed

### ISSUE THREAD

**Issue by TENX-S** [RustAudio/lewton#81]
OS:  macOS 10.15.5
Rust-version: 1.46.0-nightly

When I try `cargo run --example player /Users/tenx/Desktop/Adele - Hello.Ogg`, it panicked.

Error message output:

Opening file: /Users/tenx/Desktop/Adele - Hello.Ogg
Sample rate: 48000
Decoded packet no 0, with 0 samples.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidValue', examples/player.rs:59:19
stack backtrace:
   0:        0x1004a105e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfcd8b90c340c7298
   1:        0x1004c0a5c - core::fmt::write::hbd6bc3f5b64aa450
   2:        0x10049f537 - std::io::Write::write_fmt::h06d43ba979d3808c
   3:        0x1004a2d55 - std::panicking::default_hook::{{closure}}::h1a1f8085934ebd75
   4:        0x1004a2a92 - std::panicking::default_hook::h3d26700cb76db48c
   5:        0x1004a32ad - std::panicking::rust_panic_with_hook::h09ba49d5763726ac
   6:        0x1004a2e82 - rust_begin_unwind
   7:        0x1004c72ef - core::panicking::panic_fmt::hb7ffda4f05c808ad
   8:        0x1004c71f5 - core::option::expect_none_failed::hde54dd319ff273ef
   9:        0x1003a1951 - core::result::Result<T,E>::unwrap::h6130701b3e405988
  10:        0x10039f5ee - player::run::h2a68ce9b42167151
  11:        0x10039ea17 - player::main::h59ee7b7ea7e5af7c
  12:        0x100391a5e - std::rt::lang_start::{{closure}}::h01d18a92b6b9179d
  13:        0x1004a3579 - std::rt::lang_start_internal::he8abc698fc8e01d2
  14:        0x100391a41 - std::rt::lang_start::h20b7f5436c5bca4e
  15:        0x10039fc02 - main

**Comment by est31** [comment]
Hmm not sure where the InvalidValue message comes from. It's not in lewton's source code.

**Comment by TENX-S** [comment]
> Hmm not sure where the InvalidValue message comes from. It's not in lewton's source code.

I just clone this repo and cd into it, and modify the /path/to/your/audio.ogg to run the example. Then it happens..

**Comment by est31** [comment]
It seems to be an alto error. cc #77
