### ISSUE TITLE
Update `tinyvec` dependency to 1.0

### ISSUE THREAD

**Issue by Lokathor** [RustAudio/lewton#82]
`tinyvec` has a 1.0 out, you should update.

I'd do the PR myself, but it looks like your CI is broken right now so I don't want to throw more changes at you until you fix that.

**Comment by est31** [comment]
@Lokathor thanks for the note. The CI is broken because the server hosting the samples had an issue. They are backed up fortunately but I decided to wait until the issue was resolved.
