### ISSUE TITLE
Fixed-point support

### ISSUE THREAD

**Issue by joerg-krause** [RustAudio/lewton#9]
Is it possible to add fixed-point support so that lewton can be used on soft-float targets, too? I guess you know that Tremor and Tremolo are fixed-point C library version of libvorbis.

**Comment by est31** [comment]
Yes, I know of the two libraries.

Do you have any resources on how to generally do such ports?

**Comment by joerg-krause** [comment]
I guess there is not official specification. However, I have found [this](http://cse.csusb.edu/tongyu/research/iccsa/iccsa06_1.html) resource about implementing a fixed-width 16-bit decoder. Note, that we would need 32-bit.

Furthermore, there are some notes in the [vobis spec](https://xiph.org/vorbis/doc/Vorbis_I_spec.html) about fixed-point.

**Comment by est31** [comment]
Thanks! I'll give it a try.

**Comment by joerg-krause** [comment]
Closed, as I am not in need for this anymore.
